### ISSUE TITLE
create link bandwidth plot

### ISSUE THREAD

**Issue by billyc** [avoev-vsp/avoev-vsp.github.io#21]

**Comment by ikaddoura** [comment]
I added some files which can be used for testing:

A file with the following columns: linkId;agents_hour1;agents_hour2;...
https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/gladbeck/avoev/output-snzDrtO443g/snzDrtO443g.link_hourlyTrafficVolume_passengers_VEHICLEFILTER-pt-vehicles.csv

and the network as shape-file:
https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/gladbeck/avoev/output-snzDrtO443g/gladbeck-network/

**Comment by ikaddoura** [comment]
@billyc :-)
