### ISSUE TITLE
add widgets to link-vol plot

### ISSUE THREAD

**Issue by billyc** [avoev-vsp/avoev-vsp.github.io#41]

**Comment by billyc** [comment]
- Zeige eine Zeitraum
- Darstellung für einen Zeitraum

**Comment by billyc** [comment]
Mostly working now, I think. BUT:

- Uhrzeit is the wrong label if we are just showing "agents"

**Comment by ikaddoura** [comment]
> Mostly working now, I think. BUT:
> 
> * Uhrzeit is the wrong label if we are just showing "agents"

yes, I will get rid of these files since the hourly plots are working...

**Comment by ikaddoura** [comment]
maybe something like **"Hide lines below..."** would be nice here as well..
