### ISSUE TITLE
animation - use gladbeck thumbnail

### ISSUE THREAD

**Issue by billyc** [avoev-vsp/avoev-vsp.github.io#44]

**Comment by ikaddoura** [comment]
I tried this, but it doesn't work:

---
title: "DRT Vehicle Animation"
description: DRT vehicles
network: gladbeck-network.xml.gz
drtTrips: drt-vehicles.json
thumbnail: viz-agent-anim-thumbnail.png

**Comment by billyc** [comment]
fixed
