### ISSUE TITLE
Add traffic volume difference plot

### ISSUE THREAD

**Issue by ikaddoura** [avoev-vsp/avoev-vsp.github.io#48]
Would be nice to be able to provide two instead of just one csv file and then see the differences.

**Comment by billyc** [comment]
works

- add `csvFile2` to create a diff plot
- diff is always `csvFile2 - csvFile`; i.e. the csvFile is base and csvFile2 is project
- you can use relative paths within the project, e.g. `csvFile2="../base/my-data.csv"

We'll hold off on UI selection dropdowns etc.

NOTE: still need to add legend.
